In [1]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('cars.csv')

Inspecting dataframes

In [4]:
data.head()

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,9.0,111.0,5000.0,21,27,13495,11.190476,Medium,0,1
1,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,9.0,111.0,5000.0,21,27,16500,11.190476,Medium,0,1
2,1,122,alfa-romero,std,two,hatchback,rwd,front,94.5,0.822681,...,9.0,154.0,5000.0,19,26,16500,12.368421,Medium,0,1
3,2,164,audi,std,four,sedan,fwd,front,99.8,0.848630,...,10.0,102.0,5500.0,24,30,13950,9.791667,Medium,0,1
4,2,164,audi,std,four,sedan,4wd,front,99.4,0.848630,...,8.0,115.0,5500.0,18,22,17450,13.055556,Medium,0,1

In [6]:
data.info

<bound method DataFrame.info of      symboling  normalized-losses         make aspiration num-of-doors  \
0            3                122  alfa-romero        std          two
1            3                122  alfa-romero        std          two
2            1                122  alfa-romero        std          two
3            2                164         audi        std         four
4            2                164         audi        std         four
..         ...                ...          ...        ...          ...
196         -1                 95        volvo        std         four
197         -1                 95        volvo      turbo         four
198         -1                 95        volvo        std         four
199         -1                 95        volvo      turbo         four
200         -1                 95        volvo      turbo         four

      body-style drive-wheels engine-location  wheel-base    length  ...  \
0    convertible          rwd           front        88.6  0.811148  ...
1    convertible          rwd           front        88.6  0.811148  ...
2      hatchback          rwd           front        94.5  0.822681  ...
3          sedan          fwd           front        99.8  0.848630  ...
4          sedan          4wd           front        99.4  0.848630  ...
..           ...          ...             ...         ...       ...  ...
196        sedan          rwd           front       109.1  0.907256  ...
197        sedan          rwd           front       109.1  0.907256  ...
198        sedan          rwd           front       109.1  0.907256  ...
199        sedan          rwd           front       109.1  0.907256  ...
200        sedan          rwd           front       109.1  0.907256  ...

     compression-ratio  horsepower  peak-rpm city-mpg highway-mpg  price  \
0                  9.0       111.0    5000.0       21          27  13495
1                  9.0       111.0    5000.0       21          27  16500
2                  9.0       154.0    5000.0       19          26  16500
3                 10.0       102.0    5500.0       24          30  13950
4                  8.0       115.0    5500.0       18          22  17450
..                 ...         ...       ...      ...         ...    ...
196                9.5       114.0    5400.0       23          28  16845
197                8.7       160.0    5300.0       19          25  19045
198                8.8       134.0    5500.0       18          23  21485
199               23.0       106.0    4800.0       26          27  22470
200                9.5       114.0    5400.0       19          25  22625

    city-L/100km  horsepower-binned  diesel  gas
0      11.190476             Medium       0    1
1      11.190476             Medium       0    1
2      12.368421             Medium       0    1
3       9.791667             Medium       0    1
4      13.055556             Medium       0    1
..           ...                ...     ...  ...
196    10.217391             Medium       0    1
197    12.368421               High       0    1
198    13.055556             Medium       0    1
199     9.038462             Medium       1    0
200    12.368421             Medium       0    1

[201 rows x 29 columns]>

In [7]:
data.shape

(201, 29)

In [8]:
data.describe(include = 'object')

,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,engine-type,num-of-cylinders,fuel-system,horsepower-binned
count,201,201,201,201,201,201,201,201,201,200
unique,22,2,2,5,3,2,6,7,8,3
top,toyota,std,four,sedan,fwd,front,ohc,four,mpfi,Low
freq,32,165,115,94,118,198,145,157,92,115

In [10]:
data.columns

Index(['symboling', 'normalized-losses', 'make', 'aspiration', 'num-of-doors',
       'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length',
       'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders',
       'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio',
       'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price',
       'city-L/100km', 'horsepower-binned', 'diesel', 'gas'],
      dtype='object')

In [12]:
data.describe()

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
count,201.000000,201.00000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,197.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000
mean,0.840796,122.00000,98.797015,0.837102,0.915126,53.766667,2555.666667,126.875622,3.330692,3.256904,10.164279,103.405534,5117.665368,25.179104,30.686567,13207.129353,9.944145,0.099502,0.900498
std,1.254802,31.99625,6.066366,0.059213,0.029187,2.447822,517.296727,41.546834,0.268072,0.319256,4.004965,37.365700,478.113805,6.423220,6.815150,7947.066342,2.534599,0.300083,0.300083
min,-2.000000,65.00000,86.600000,0.678039,0.837500,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000,4.795918,0.000000,0.000000
25%,0.000000,101.00000,94.500000,0.801538,0.890278,52.000000,2169.000000,98.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7775.000000,7.833333,0.000000,1.000000
50%,1.000000,122.00000,97.000000,0.832292,0.909722,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5125.369458,24.000000,30.000000,10295.000000,9.791667,0.000000,1.000000
75%,2.000000,137.00000,102.400000,0.881788,0.925000,55.500000,2926.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16500.000000,12.368421,0.000000,1.000000
max,3.000000,256.00000,120.900000,1.000000,1.000000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,262.000000,6600.000000,49.000000,54.000000,45400.000000,18.076923,1.000000,1.000000

In [13]:
data.index

RangeIndex(start=0, stop=201, step=1)

In [14]:
data.values

array([[3, 122, 'alfa-romero', ..., 'Medium', 0, 1],
       [3, 122, 'alfa-romero', ..., 'Medium', 0, 1],
       [1, 122, 'alfa-romero', ..., 'Medium', 0, 1],
       ...,
       [-1, 95, 'volvo', ..., 'Medium', 0, 1],
       [-1, 95, 'volvo', ..., 'Medium', 1, 0],
       [-1, 95, 'volvo', ..., 'Medium', 0, 1]], dtype=object)

sorting

In [15]:
data.head()

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,9.0,111.0,5000.0,21,27,13495,11.190476,Medium,0,1
1,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,9.0,111.0,5000.0,21,27,16500,11.190476,Medium,0,1
2,1,122,alfa-romero,std,two,hatchback,rwd,front,94.5,0.822681,...,9.0,154.0,5000.0,19,26,16500,12.368421,Medium,0,1
3,2,164,audi,std,four,sedan,fwd,front,99.8,0.848630,...,10.0,102.0,5500.0,24,30,13950,9.791667,Medium,0,1
4,2,164,audi,std,four,sedan,4wd,front,99.4,0.848630,...,8.0,115.0,5500.0,18,22,17450,13.055556,Medium,0,1

In [16]:
data.sort_values("price").head()

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
134,2,83,subaru,std,two,hatchback,fwd,front,93.7,0.753964,...,9.0,69.0,4900.0,31,36,5118,7.580645,Low,0,1
17,2,121,chevrolet,std,two,hatchback,fwd,front,88.4,0.678039,...,9.5,48.0,5100.0,47,53,5151,5.000000,Low,0,1
47,1,104,mazda,std,two,hatchback,fwd,front,93.1,0.764536,...,9.0,68.0,5000.0,30,31,5195,7.833333,Low,0,1
146,1,87,toyota,std,two,hatchback,fwd,front,95.7,0.762614,...,9.0,62.0,4800.0,35,39,5348,6.714286,Low,0,1
73,2,161,mitsubishi,std,two,hatchback,fwd,front,93.7,0.755887,...,9.4,68.0,5500.0,37,41,5389,6.351351,Low,0,1

In [17]:
data.sort_values("price", ascending = False).head()

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
71,1,122,mercedes-benz,std,two,hardtop,rwd,front,112.0,0.957232,...,8.0,184.0,4500.0,14,16,45400,16.785714,High,0,1
15,0,122,bmw,std,two,sedan,rwd,front,103.5,0.931283,...,8.0,182.0,5400.0,16,22,41315,14.687500,High,0,1
70,0,122,mercedes-benz,std,four,sedan,rwd,front,120.9,1.000000,...,8.0,184.0,4500.0,14,16,40960,16.785714,High,0,1
125,3,122,porsche,std,two,convertible,rwd,rear,89.5,0.811629,...,9.5,207.0,5900.0,17,25,37028,13.823529,High,0,1
16,0,122,bmw,std,four,sedan,rwd,front,110.0,0.946660,...,8.0,182.0,5400.0,15,20,36880,15.666667,High,0,1

subsetting

In [29]:
print(data[["make", "num-of-doors", "body-style", "engine-location", "horsepower", "price", "diesel", "gas"]].head())

          make num-of-doors   body-style engine-location  horsepower  price  \
0  alfa-romero          two  convertible           front       111.0  13495
1  alfa-romero          two  convertible           front       111.0  16500
2  alfa-romero          two    hatchback           front       154.0  16500
3         audi         four        sedan           front       102.0  13950
4         audi         four        sedan           front       115.0  17450

   diesel  gas
0       0    1
1       0    1
2       0    1
3       0    1
4       0    1

In [31]:
data[data['body-style'] == "sedan"].head()

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
3,2,164,audi,std,four,sedan,fwd,front,99.8,0.848630,...,10.0,102.0,5500.0,24,30,13950,9.791667,Medium,0,1
4,2,164,audi,std,four,sedan,4wd,front,99.4,0.848630,...,8.0,115.0,5500.0,18,22,17450,13.055556,Medium,0,1
5,2,122,audi,std,two,sedan,fwd,front,99.8,0.851994,...,8.5,110.0,5500.0,19,25,15250,12.368421,Medium,0,1
6,1,158,audi,std,four,sedan,fwd,front,105.8,0.925997,...,8.5,110.0,5500.0,19,25,17710,12.368421,Medium,0,1
8,1,158,audi,turbo,four,sedan,fwd,front,105.8,0.925997,...,8.3,140.0,5500.0,17,20,23875,13.823529,Medium,0,1

In [35]:
data[data['price'] <= 10000].head(20)

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
17,2,121,chevrolet,std,two,hatchback,fwd,front,88.4,0.678039,...,9.50,48.0,5100.0,47,53,5151,5.000000,Low,0,1
18,1,98,chevrolet,std,two,hatchback,fwd,front,94.5,0.749159,...,9.60,70.0,5400.0,38,43,6295,6.184211,Low,0,1
19,0,81,chevrolet,std,four,sedan,fwd,front,94.5,0.763095,...,9.60,70.0,5400.0,38,43,6575,6.184211,Low,0,1
20,1,118,dodge,std,two,hatchback,fwd,front,93.7,0.755887,...,9.41,68.0,5500.0,37,41,5572,6.351351,Low,0,1
21,1,118,dodge,std,two,hatchback,fwd,front,93.7,0.755887,...,9.40,68.0,5500.0,31,38,6377,7.580645,Low,0,1
22,1,118,dodge,turbo,two,hatchback,fwd,front,93.7,0.755887,...,7.60,102.0,5500.0,24,30,7957,9.791667,Medium,0,1
23,1,148,dodge,std,four,hatchback,fwd,front,93.7,0.755887,...,9.40,68.0,5500.0,31,38,6229,7.580645,Low,0,1
24,1,148,dodge,std,four,sedan,fwd,front,93.7,0.755887,...,9.40,68.0,5500.0,31,38,6692,7.580645,Low,0,1
25,1,148,dodge,std,four,sedan,fwd,front,93.7,0.755887,...,9.40,68.0,5500.0,31,38,7609,7.580645,Low,0,1
26,1,148,dodge,turbo,four,sedan,fwd,front,93.7,0.755887,...,7.60,102.0,5500.0,24,30,8558,9.791667,Medium,0,1
27,-1,110,dodge,std,four,wagon,fwd,front,103.3,0.839020,...,8.50,88.0,5000.0,24,30,8921,9.791667,Low,0,1
29,2,137,honda,std,two,hatchback,fwd,front,86.6,0.694858,...,9.60,58.0,4800.0,49,54,6479,4.795918,Low,0,1
30,2,137,honda,std,two,hatchback,fwd,front,86.6,0.694858,...,9.20,76.0,6000.0,31,38,6855,7.580645,Low,0,1
31,1,101,honda,std,two,hatchback,fwd,front,93.7,0.720807,...,10.10,60.0,5500.0,38,42,5399,6.184211,Low,0,1
32,1,101,honda,std,two,hatchback,fwd,front,93.7,0.720807,...,9.20,76.0,6000.0,30,34,6529,7.833333,Low,0,1
33,1,101,honda,std,two,hatchback,fwd,front,93.7,0.720807,...,9.20,76.0,6000.0,30,34,7129,7.833333,Low,0,1
34,0,110,honda,std,four,sedan,fwd,front,96.5,0.785199,...,9.20,76.0,6000.0,30,34,7295,7.833333,Low,0,1
35,0,78,honda,std,four,wagon,fwd,front,96.5,0.754926,...,9.20,76.0,6000.0,30,34,7295,7.833333,Low,0,1
36,0,106,honda,std,two,hatchback,fwd,front,96.5,0.804901,...,9.00,86.0,5800.0,27,33,7895,8.703704,Low,0,1
37,0,106,honda,std,two,hatchback,fwd,front,96.5,0.804901,...,9.00,86.0,5800.0,27,33,9095,8.703704,Low,0,1

In [36]:
data["length_100"] = data["length"] * 100

In [37]:
data.head()

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas,length_100
0,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,111.0,5000.0,21,27,13495,11.190476,Medium,0,1,81.114849
1,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,111.0,5000.0,21,27,16500,11.190476,Medium,0,1,81.114849
2,1,122,alfa-romero,std,two,hatchback,rwd,front,94.5,0.822681,...,154.0,5000.0,19,26,16500,12.368421,Medium,0,1,82.268140
3,2,164,audi,std,four,sedan,fwd,front,99.8,0.848630,...,102.0,5500.0,24,30,13950,9.791667,Medium,0,1,84.863047
4,2,164,audi,std,four,sedan,4wd,front,99.4,0.848630,...,115.0,5500.0,18,22,17450,13.055556,Medium,0,1,84.863047

summary statistics

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          201 non-null    int64
 1   normalized-losses  201 non-null    int64
 2   make               201 non-null    object
 3   aspiration         201 non-null    object
 4   num-of-doors       201 non-null    object
 5   body-style         201 non-null    object
 6   drive-wheels       201 non-null    object
 7   engine-location    201 non-null    object
 8   wheel-base         201 non-null    float64
 9   length             201 non-null    float64
 10  width              201 non-null    float64
 11  height             201 non-null    float64
 12  curb-weight        201 non-null    int64
 13  engine-type        201 non-null    object
 14  num-of-cylinders   201 non-null    object
 15  engine-size        201 non-null    int64
 16  fuel-system        201 non-null    object
 17  bore               201 non-null    float64
 18  stroke             197 non-null    float64
 19  compression-ratio  201 non-null    float64
 20  horsepower         201 non-null    float64
 21  peak-rpm           201 non-null    float64
 22  city-mpg           201 non-null    int64
 23  highway-mpg        201 non-null    int64
 24  price              201 non-null    int64
 25  city-L/100km       201 non-null    float64
 26  horsepower-binned  200 non-null    object
 27  diesel             201 non-null    int64
 28  gas                201 non-null    int64
 29  length_100         201 non-null    float64
dtypes: float64(11), int64(9), object(10)
memory usage: 47.2+ KB

In [40]:
data["price"].mean()

13207.129353233831

In [43]:
data["length_100"].mean()

83.71023307412933

In [44]:
data["price"].median()

10295.0

In [45]:
#a custom IQR function
def iqr(column):
    return column.quantile(0.75) - column.quantile(0.25)

In [47]:
iqr(data["price"])

8725.0